version: '2'

services:
  api:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: api_container
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SOLO_DB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:12.2-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=SOLO_DB
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ../../../React/solo-app-frontend
    container_name: front_container
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true